/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.univ.pharmasys.ui;

import java.math.BigDecimal;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;

import javax.swing.JOptionPane;

import br.univ.pharmasys.dao.MedicamentoDAO;
import br.univ.pharmasys.model.Medicamento;

/**
 *
 * @author kessy
 */
public class TelaCadastroDeEstoque extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroDeEstoque.class.getName());

    /**
     * Creates new form TelaCadastroDeEstoque
     */
    public TelaCadastroDeEstoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        PanelMedicamento = new javax.swing.JPanel();
        LabelMedicamento = new javax.swing.JLabel();
        CampoNomeComercial = new javax.swing.JTextField();
        CampoSKU = new javax.swing.JTextField();
        CampoDosagem = new javax.swing.JTextField();
        CampoPrincipioAtivo = new javax.swing.JTextField();
        CampoEstoqueMinimo = new javax.swing.JTextField();
        CampoEstoqueMaximo = new javax.swing.JTextField();
        ComboBoxForma = new javax.swing.JComboBox<>();
        CampoEstoqueAtual = new javax.swing.JTextField();
        CampoPreco = new javax.swing.JTextField();
        ButtonCancelar = new javax.swing.JButton();
        ButtonCadastrar = new javax.swing.JButton();
        LabelCadastroDeEstoque = new javax.swing.JLabel();
        CampoDataExpiracao = new javax.swing.JTextField();

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TelaCadEstoque");
        setResizable(false);

        PanelMedicamento.setBackground(new java.awt.Color(255, 255, 255));

        LabelMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelMedicamento.setText("Medicamento");

        CampoNomeComercial.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome Comercial"));
        CampoNomeComercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeComercialActionPerformed(evt);
            }
        });

        CampoSKU.setBorder(javax.swing.BorderFactory.createTitledBorder("SKU"));
        CampoSKU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoSKUActionPerformed(evt);
            }
        });

        CampoDosagem.setBorder(javax.swing.BorderFactory.createTitledBorder("Dosagem"));
        CampoDosagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDosagemActionPerformed(evt);
            }
        });

        CampoPrincipioAtivo.setBorder(javax.swing.BorderFactory.createTitledBorder("Princípio Ativo"));

        CampoEstoqueMinimo.setBorder(javax.swing.BorderFactory.createTitledBorder("Estoque Mínimo"));

        CampoEstoqueMaximo.setBorder(javax.swing.BorderFactory.createTitledBorder("Estoque Máximo"));

        ComboBoxForma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sólido", "Semissólido", "Líquido", "Gasoso", "Injetável" }));
        ComboBoxForma.setBorder(javax.swing.BorderFactory.createTitledBorder("Forma"));

        CampoEstoqueAtual.setBorder(javax.swing.BorderFactory.createTitledBorder("Estoque Atual"));

        CampoPreco.setBorder(javax.swing.BorderFactory.createTitledBorder("Preço"));
        CampoPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPrecoActionPerformed(evt);
            }
        });

        ButtonCancelar.setText("Cancelar");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        ButtonCadastrar.setText("Cadastrar");
        ButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastrarActionPerformed(evt);
            }
        });

        LabelCadastroDeEstoque.setBackground(new java.awt.Color(51, 51, 51));
        LabelCadastroDeEstoque.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LabelCadastroDeEstoque.setText("Cadastro De Estoque");

        CampoDataExpiracao.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de Expiração"));

        javax.swing.GroupLayout PanelMedicamentoLayout = new javax.swing.GroupLayout(PanelMedicamento);
        PanelMedicamento.setLayout(PanelMedicamentoLayout);
        PanelMedicamentoLayout.setHorizontalGroup(
            PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMedicamentoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMedicamentoLayout.createSequentialGroup()
                        .addComponent(ButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonCadastrar)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMedicamentoLayout.createSequentialGroup()
                        .addComponent(LabelCadastroDeEstoque)
                        .addGap(203, 203, 203))))
            .addGroup(PanelMedicamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMedicamentoLayout.createSequentialGroup()
                        .addGroup(PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelMedicamentoLayout.createSequentialGroup()
                                .addComponent(CampoNomeComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CampoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelMedicamentoLayout.createSequentialGroup()
                                .addComponent(CampoSKU, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CampoEstoqueMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(PanelMedicamentoLayout.createSequentialGroup()
                                    .addComponent(CampoDosagem, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(CampoEstoqueMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PanelMedicamentoLayout.createSequentialGroup()
                                    .addGroup(PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CampoPrincipioAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ComboBoxForma, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CampoEstoqueAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                                        .addComponent(CampoDataExpiracao)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelMedicamentoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LabelMedicamento)
                        .addGap(261, 261, 261))))
        );
        PanelMedicamentoLayout.setVerticalGroup(
            PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMedicamentoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(LabelCadastroDeEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelMedicamento)
                .addGap(24, 24, 24)
                .addGroup(PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoNomeComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoSKU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoEstoqueMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoDosagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoEstoqueMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoEstoqueAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoPrincipioAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CampoDataExpiracao)
                    .addComponent(ComboBoxForma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCadastrar)
                    .addComponent(ButtonCancelar))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMedicamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNomeComercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeComercialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeComercialActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void CampoSKUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoSKUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoSKUActionPerformed

    private void CampoDosagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDosagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoDosagemActionPerformed

    private void CampoPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPrecoActionPerformed

    private void ButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastrarActionPerformed
       try {
    Medicamento med = new Medicamento();
        med.setNomeComercial(CampoNomeComercial.getText());
        med.setSku(CampoSKU.getText());
        med.setDosagem(CampoDosagem.getText());
        med.setFormaFarmaceutica(ComboBoxForma.getSelectedItem().toString());
        //med.setLaboratorio(CampoLaboratorio.getText());

        med.setEstoqueMax(Integer.parseInt(CampoEstoqueMaximo.getText().trim()));
        med.setEstoqueMin(Integer.parseInt(CampoEstoqueMinimo.getText().trim()));
        med.setEstoqueAtual(Integer.parseInt(CampoEstoqueAtual.getText().trim()));

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String dataTxt = CampoDataExpiracao.getText().trim();
        med.setDataExpiracao(LocalDate.parse(dataTxt, formatter));

        String precoTxt = CampoPreco.getText().trim().replace(",", ".");
        med.setPreco(new BigDecimal(precoTxt));

        MedicamentoDAO dao = new MedicamentoDAO();
        dao.create(med);

        JOptionPane.showMessageDialog(this, "Medicamento cadastrado com sucesso!");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(
            this,
            "Erro ao cadastrar medicamento:\n" + e.getMessage(),
            "Erro",
            JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_ButtonCadastrarActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
    this.dispose();
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastroDeEstoque().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCadastrar;
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JTextField CampoDataExpiracao;
    private javax.swing.JTextField CampoDosagem;
    private javax.swing.JTextField CampoEstoqueAtual;
    private javax.swing.JTextField CampoEstoqueMaximo;
    private javax.swing.JTextField CampoEstoqueMinimo;
    private javax.swing.JTextField CampoNomeComercial;
    private javax.swing.JTextField CampoPreco;
    private javax.swing.JTextField CampoPrincipioAtivo;
    private javax.swing.JTextField CampoSKU;
    private javax.swing.JComboBox<String> ComboBoxForma;
    private javax.swing.JLabel LabelCadastroDeEstoque;
    private javax.swing.JLabel LabelMedicamento;
    private javax.swing.JPanel PanelMedicamento;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
