/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.univ.pharmasys.ui;

import javax.swing.JFrame;

/**
 *
 * @author kessy
 */
public class TelaCadastroDeEstoque extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroDeEstoque.class.getName());

    /**
     * Creates new form TelaCadastroDeEstoque
     */
    public TelaCadastroDeEstoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        PanelMedicamento = new javax.swing.JPanel();
        LabelMedicamento = new javax.swing.JLabel();
        CampoNomeComercial = new javax.swing.JTextField();
        CampoSKU = new javax.swing.JTextField();
        CampoDosagem = new javax.swing.JTextField();
        CampoPrincipioAtivo = new javax.swing.JTextField();
        CampoEstoqueMinimo = new javax.swing.JTextField();
        CampoEstoqueMaximo = new javax.swing.JTextField();
        ComboBoxForma = new javax.swing.JComboBox<>();
        CampoEstoqueAtual = new javax.swing.JTextField();
        CampoPreco = new javax.swing.JTextField();
        ButtonCancelar = new javax.swing.JButton();
        ButtonCadastrar = new javax.swing.JButton();
        LabelCadastroDeEstoque = new javax.swing.JLabel();

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        setTitle("TelaCadEstoque");
        setResizable(false);

        PanelMedicamento.setBackground(new java.awt.Color(255, 255, 255));

        LabelMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelMedicamento.setText("Medicamento");

        CampoNomeComercial.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome Comercial"));
        CampoNomeComercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeComercialActionPerformed(evt);
            }
        });

        CampoSKU.setBorder(javax.swing.BorderFactory.createTitledBorder("SKU"));
        CampoSKU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoSKUActionPerformed(evt);
            }
        });

        CampoDosagem.setBorder(javax.swing.BorderFactory.createTitledBorder("Dosagem"));
        CampoDosagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDosagemActionPerformed(evt);
            }
        });

        CampoPrincipioAtivo.setBorder(javax.swing.BorderFactory.createTitledBorder("Princípio Ativo"));

        CampoEstoqueMinimo.setBorder(javax.swing.BorderFactory.createTitledBorder("Estoque Mínimo"));

        CampoEstoqueMaximo.setBorder(javax.swing.BorderFactory.createTitledBorder("Estoque Máximo"));

        ComboBoxForma.setBackground(new java.awt.Color(255, 255, 255));
        ComboBoxForma.setForeground(new java.awt.Color(0, 0, 0));
        ComboBoxForma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sólido", "Semissólido", "Líquido", "Gasoso", "Injetável" }));
        ComboBoxForma.setBorder(javax.swing.BorderFactory.createTitledBorder("Forma"));

        CampoEstoqueAtual.setBorder(javax.swing.BorderFactory.createTitledBorder("Estoque Atual"));

        CampoPreco.setBorder(javax.swing.BorderFactory.createTitledBorder("Preço"));
        CampoPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPrecoActionPerformed(evt);
            }
        });

        ButtonCancelar.setText("Cancelar");

        ButtonCadastrar.setText("Cadastrar");
        ButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastrarActionPerformed(evt);
            }
        });

        LabelCadastroDeEstoque.setBackground(new java.awt.Color(51, 51, 51));
        LabelCadastroDeEstoque.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LabelCadastroDeEstoque.setText("Cadastro De Estoque");

        javax.swing.GroupLayout PanelMedicamentoLayout = new javax.swing.GroupLayout(PanelMedicamento);
        PanelMedicamento.setLayout(PanelMedicamentoLayout);
        PanelMedicamentoLayout.setHorizontalGroup(
            PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMedicamentoLayout.createSequentialGroup()
                .addGroup(PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMedicamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CampoNomeComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CampoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelMedicamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CampoSKU, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CampoEstoqueMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelMedicamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(PanelMedicamentoLayout.createSequentialGroup()
                                .addComponent(CampoPrincipioAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CampoEstoqueAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelMedicamentoLayout.createSequentialGroup()
                                .addComponent(CampoDosagem, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CampoEstoqueMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelMedicamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMedicamentoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LabelMedicamento)
                        .addGap(261, 261, 261))
                    .addGroup(PanelMedicamentoLayout.createSequentialGroup()
                        .addComponent(ComboBoxForma, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMedicamentoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMedicamentoLayout.createSequentialGroup()
                        .addComponent(ButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonCadastrar)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMedicamentoLayout.createSequentialGroup()
                        .addComponent(LabelCadastroDeEstoque)
                        .addGap(203, 203, 203))))
        );
        PanelMedicamentoLayout.setVerticalGroup(
            PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMedicamentoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(LabelCadastroDeEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelMedicamento)
                .addGap(24, 24, 24)
                .addGroup(PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoNomeComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoSKU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoEstoqueMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoDosagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoEstoqueMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoEstoqueAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoPrincipioAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMedicamentoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonCadastrar)
                            .addComponent(ButtonCancelar))
                        .addGap(17, 17, 17))
                    .addGroup(PanelMedicamentoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(95, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMedicamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNomeComercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeComercialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeComercialActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void CampoSKUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoSKUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoSKUActionPerformed

    private void CampoDosagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDosagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoDosagemActionPerformed

    private void CampoPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPrecoActionPerformed

    private void ButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastroDeEstoque().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCadastrar;
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JTextField CampoDosagem;
    private javax.swing.JTextField CampoEstoqueAtual;
    private javax.swing.JTextField CampoEstoqueMaximo;
    private javax.swing.JTextField CampoEstoqueMinimo;
    private javax.swing.JTextField CampoNomeComercial;
    private javax.swing.JTextField CampoPreco;
    private javax.swing.JTextField CampoPrincipioAtivo;
    private javax.swing.JTextField CampoSKU;
    private javax.swing.JComboBox<String> ComboBoxForma;
    private javax.swing.JLabel LabelCadastroDeEstoque;
    private javax.swing.JLabel LabelMedicamento;
    private javax.swing.JPanel PanelMedicamento;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
