-- Banco de Dados: pharmasys
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE;
SET SQL_MODE='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS pharmasys DEFAULT CHARACTER SET utf8mb4;
USE pharmasys;

-- -----------------------------------------------------
-- TABELA TELEFONE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TELEFONE (
   TELEFONE_ID INT NOT NULL AUTO_INCREMENT,
   NUMERO VARCHAR(15) NOT NULL,
   PRIMARY KEY (TELEFONE_ID)
   ) ENGINE=InnoDB;

-- -----------------------------------------------------
-- TABELA FORNECEDOR
-- (telefone do fornecedor referencia TELEFONE)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS FORNECEDOR (
    ID_FORNECEDOR INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CNPJ VARCHAR(20) NOT NULL,
    ENDERECO VARCHAR(150),
    TELEFONE_ID INT,
    EMAIL VARCHAR(100),
    INATIVO TINYINT DEFAULT 0,
    PRIMARY KEY (ID_FORNECEDOR),
    UNIQUE (CNPJ),
    CONSTRAINT fk_fornecedor_telefone
    FOREIGN KEY (TELEFONE_ID)
    REFERENCES TELEFONE (TELEFONE_ID)
    ON UPDATE CASCADE
    ON DELETE SET NULL
    ) ENGINE=InnoDB;

-- -----------------------------------------------------
-- TABELA FUNCIONARIO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS FUNCIONARIO (
    ID_FUNCIONARIO INT NOT NULL AUTO_INCREMENT,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    DATA_NASCIMENTO DATE,
    SEXO VARCHAR(10),
    NOME VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(150),
    SENHA VARCHAR(255),
    TIPO INT NOT NULL,        -- 1=Atendente, 2=Farmacêutico, 3=Gerente
    TELEFONE_ID INT NOT NULL,
    PRIMARY KEY (ID_FUNCIONARIO),
    CONSTRAINT fk_funcionario_telefone
    FOREIGN KEY (TELEFONE_ID)
    REFERENCES TELEFONE (TELEFONE_ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    ) ENGINE=InnoDB;

-- -----------------------------------------------------
-- TABELA DEPENDENTE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DEPENDENTE (
    ID_DEPENDENTE INT NOT NULL AUTO_INCREMENT,
    CPF VARCHAR(11) NOT NULL,
    NOME VARCHAR(200),
    SEXO VARCHAR(10),
    DATA_NASCIMENTO DATE,
    FUNCIONARIO_ID INT NOT NULL,
    PRIMARY KEY (ID_DEPENDENTE),
    CONSTRAINT fk_dependente_funcionario
    FOREIGN KEY (FUNCIONARIO_ID)
    REFERENCES FUNCIONARIO (ID_FUNCIONARIO)
    ON DELETE CASCADE
    ) ENGINE=InnoDB;

-- -----------------------------------------------------
-- TABELA PEDIDO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS PEDIDO (
    ID_PEDIDO INT NOT NULL AUTO_INCREMENT,
    QUANTIDADE INT NOT NULL,
    STATUS ENUM('PENDENTE','FINALIZADO','CANCELADO'),
    DATA DATE,
    PRECO_UNITARIO DECIMAL(10,2),
    VALOR_TOTAL DECIMAL(10,2),
    PRIMARY KEY (ID_PEDIDO)
    ) ENGINE=InnoDB;

-- -----------------------------------------------------
-- TABELA APROVA (N x N)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS APROVA (
    FUNCIONARIO_ID INT NOT NULL,
    PEDIDO_ID INT NOT NULL,
    PRIMARY KEY (FUNCIONARIO_ID, PEDIDO_ID),
    CONSTRAINT fk_aprova_funcionario
    FOREIGN KEY (FUNCIONARIO_ID)
    REFERENCES FUNCIONARIO (ID_FUNCIONARIO),
    CONSTRAINT fk_aprova_pedido
    FOREIGN KEY (PEDIDO_ID)
    REFERENCES PEDIDO (ID_PEDIDO)
    ) ENGINE=InnoDB;

-- -----------------------------------------------------
-- TABELA MEDICAMENTO
-- Observação: não contém LOTE_ID, DATA_EXPIRACAO nem PRECO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS MEDICAMENTO (
    SKU VARCHAR(45) NOT NULL,
    CODIGO_BARRAS VARCHAR(20) NOT NULL UNIQUE,
    NOME_COMERCIAL VARCHAR(100) NOT NULL,
    FORMA_FARMACEUTICA VARCHAR(45) NOT NULL,
    DOSAGEM VARCHAR(45) NOT NULL,
    FABRICANTE VARCHAR(100) NOT NULL,
    LABORATORIO VARCHAR(100),
    ESTOQUE_MIN INT DEFAULT 0,
    ESTOQUE_MAX INT DEFAULT 0,
    PRIMARY KEY (SKU)
    ) ENGINE=InnoDB;

-- -----------------------------------------------------
-- TABELA LOTE
-- Cada lote referencia o medicamento (SKU) e pode opcionalmente ter fornecedor
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS LOTE (
    NUMERO_LOTE INT NOT NULL AUTO_INCREMENT,
    SKU_MEDICAMENTO VARCHAR(45) NOT NULL,
    FORNECEDOR_ID INT DEFAULT NULL,
    VALIDADE DATE,
    DATA_RECEBIMENTO DATE,
    QUANTIDADE_RECEBIDA INT NOT NULL,
    QUANTIDADE_ATUAL INT DEFAULT 0,
    PRECO DECIMAL(10,2),
    PRIMARY KEY (NUMERO_LOTE),
    CONSTRAINT fk_lote_medicamento
    FOREIGN KEY (SKU_MEDICAMENTO) REFERENCES MEDICAMENTO (SKU)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
    CONSTRAINT fk_lote_fornecedor
    FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDOR (ID_FORNECEDOR)
    ON UPDATE CASCADE
    ON DELETE SET NULL
    ) ENGINE=InnoDB;

-- -----------------------------------------------------
-- TABELA FORNECE (N x N) - mantém fornecedor ↔ medicamento (se desejado)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS FORNECE (
    MEDICAMENTO_SKU VARCHAR(45) NOT NULL,
    FORNECEDOR_ID INT NOT NULL,
    PRIMARY KEY (MEDICAMENTO_SKU, FORNECEDOR_ID),
    CONSTRAINT fk_fornece_medicamento
    FOREIGN KEY (MEDICAMENTO_SKU) REFERENCES MEDICAMENTO (SKU),
    CONSTRAINT fk_fornece_fornecedor
    FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDOR (ID_FORNECEDOR)
    ) ENGINE=InnoDB;

-- -----------------------------------------------------
-- TABELA CLIENTE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CLIENTE (
    CPF_CLIENTE VARCHAR(11) NOT NULL,
    SEXO VARCHAR(10),
    NOME VARCHAR(200),
    PRIMARY KEY (CPF_CLIENTE)
    ) ENGINE=InnoDB;

-- -----------------------------------------------------
-- TABELA DUVIDAS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DUVIDAS (
    ID_DUVIDA INT NOT NULL AUTO_INCREMENT,
    DATA_PERGUNTA DATE NOT NULL,
    RESPONDIDO ENUM('SIM','NAO') NOT NULL,
    CPF_CLIENTE VARCHAR(11) NOT NULL,
    PRIMARY KEY (ID_DUVIDA),
    CONSTRAINT fk_duvidas_cliente
    FOREIGN KEY (CPF_CLIENTE)
    REFERENCES CLIENTE (CPF_CLIENTE)
    ) ENGINE=InnoDB;

-- -----------------------------------------------------
-- TABELA RESPONDE (N x N)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS RESPONDE (
    FUNCIONARIO_ID INT NOT NULL,
    DUVIDA_ID INT NOT NULL,
    PRIMARY KEY (FUNCIONARIO_ID, DUVIDA_ID),
    CONSTRAINT fk_responde_funcionario
    FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIO(ID_FUNCIONARIO),
    CONSTRAINT fk_responde_duvida
    FOREIGN KEY (DUVIDA_ID) REFERENCES DUVIDAS(ID_DUVIDA)
    ) ENGINE=InnoDB;

-- -----------------------------------------------------
-- TABELA ATENDIMENTO (N x N x N)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ATENDIMENTO (
    PEDIDO_ID INT NOT NULL,
    FUNCIONARIO_ID INT NOT NULL,
    CLIENTE_CPF VARCHAR(11) NOT NULL,
    PRIMARY KEY (PEDIDO_ID, FUNCIONARIO_ID, CLIENTE_CPF),
    CONSTRAINT fk_atendimento_pedido
    FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID_PEDIDO),
    CONSTRAINT fk_atendimento_funcionario
    FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIO(ID_FUNCIONARIO),
    CONSTRAINT fk_atendimento_cliente
    FOREIGN KEY (CLIENTE_CPF) REFERENCES CLIENTE(CPF_CLIENTE)
    ) ENGINE=InnoDB;

-- -----------------------------------------------------
-- TABELA SUPERVISAO (N x N)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS SUPERVISAO (
    SUPERVISOR_ID INT NOT NULL,
    SUPERVISIONADO_ID INT NOT NULL,
    PRIMARY KEY (SUPERVISOR_ID, SUPERVISIONADO_ID),
    CONSTRAINT fk_supervisao_supervisor
    FOREIGN KEY (SUPERVISOR_ID) REFERENCES FUNCIONARIO(ID_FUNCIONARIO),
    CONSTRAINT fk_supervisao_supervisionado
    FOREIGN KEY (SUPERVISIONADO_ID) REFERENCES FUNCIONARIO(ID_FUNCIONARIO)
    ) ENGINE=InnoDB;

-- -----------------------------------------------------
-- TABELA RECEITA_RETIDA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS RECEITA_RETIDA (
    ID_RECEITA INT NOT NULL AUTO_INCREMENT,
    CRM_MEDICO VARCHAR(10) NOT NULL,
    DADOS_PACIENTE VARCHAR(100),
    DATA_EMITIDA DATE,
    NOME_MEDICO VARCHAR(200),
    NOME_MEDICAMENTO VARCHAR(100),
    PRIMARY KEY (ID_RECEITA)
    ) ENGINE=InnoDB;

-- -----------------------------------------------------
-- TABELA EXIGE (N x N)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS EXIGE (
    RECEITA_ID INT NOT NULL,
    MEDICAMENTO_SKU VARCHAR(45) NOT NULL,
    PRIMARY KEY (RECEITA_ID, MEDICAMENTO_SKU),
    CONSTRAINT fk_exige_receita
    FOREIGN KEY (RECEITA_ID) REFERENCES RECEITA_RETIDA(ID_RECEITA),
    CONSTRAINT fk_exige_medicamento
    FOREIGN KEY (MEDICAMENTO_SKU) REFERENCES MEDICAMENTO(SKU)
    ) ENGINE=InnoDB;

-- -----------------------------------------------------
-- TABELA REFERE_SE (N x N)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS REFERE_SE (
    PEDIDO_ID INT NOT NULL,
    MEDICAMENTO_SKU VARCHAR(45) NOT NULL,
    PRIMARY KEY (PEDIDO_ID, MEDICAMENTO_SKU),
    CONSTRAINT fk_refere_pedido
    FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID_PEDIDO),
    CONSTRAINT fk_refere_medicamento
    FOREIGN KEY (MEDICAMENTO_SKU) REFERENCES MEDICAMENTO(SKU)
    ) ENGINE=InnoDB;

-- -----------------------------------------------------
-- TABELA PAGAMENTO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS PAGAMENTO (
    ID_PAGAMENTO INT NOT NULL AUTO_INCREMENT,
    PEDIDO_ID INT NOT NULL,
    METODO_PAGAMENTO ENUM('DINHEIRO','CARTAO_CREDITO','CARTAO_DEBITO','PIX','OUTRO') NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    DATA_PAGAMENTO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    QRCODE VARCHAR(500) NULL,
    CODIGO_BARRAS VARCHAR(50) NULL,
    PRIMARY KEY (ID_PAGAMENTO),
    CONSTRAINT fk_pagamento_pedido
    FOREIGN KEY (PEDIDO_ID)
    REFERENCES PEDIDO(ID_PEDIDO)
    ON UPDATE CASCADE
    ON DELETE CASCADE
    ) ENGINE=InnoDB;

-- -----------------------------------------------------
-- VIEW: Estoque atual por medicamento (soma de lotes)
-- -----------------------------------------------------
DROP VIEW IF EXISTS VW_ESTOQUE_MEDICAMENTO;
CREATE VIEW VW_ESTOQUE_MEDICAMENTO AS
SELECT
    M.SKU,
    M.NOME_COMERCIAL,
    COALESCE(SUM(L.QUANTIDADE_ATUAL), 0) AS ESTOQUE_ATUAL,
    M.ESTOQUE_MIN,
    M.ESTOQUE_MAX
FROM MEDICAMENTO M
         LEFT JOIN LOTE L ON L.SKU_MEDICAMENTO = M.SKU
GROUP BY M.SKU, M.NOME_COMERCIAL, M.ESTOQUE_MIN, M.ESTOQUE_MAX;


CREATE INDEX IF NOT EXISTS IDX_LOTE_SKU ON LOTE (SKU_MEDICAMENTO);
CREATE INDEX IF NOT EXISTS IDX_FORNECEDOR_CNPJ ON FORNECEDOR (CNPJ);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
